export const adminStyles = `
:root{color-scheme:light;--brand:#734921;--ink:#302c26;--muted:#716b60;--line:#ded7cb;--paper:#fffdf8}
*{box-sizing:border-box}body{margin:0 auto;padding:36px;max-width:920px;background:#efe9dd;color:var(--ink);font:16px/1.65 -apple-system,"PingFang TC","Noto Sans TC",sans-serif}
h1{font-size:24px;line-height:1.3;color:var(--brand);margin:0 0 8px}h2,h3,.sec-title{font-size:18px;font-weight:650;color:var(--brand);margin:0 0 12px}h4{font-size:16px;margin:20px 0 8px}p{margin:8px 0}button,input,select{font:inherit}button,select{cursor:pointer}a,button,input,select,summary{touch-action:manipulation}a:focus-visible,button:focus-visible,input:focus-visible,select:focus-visible,summary:focus-visible{outline:3px solid #99682f;outline-offset:3px}[hidden]{display:none!important}
.sub,.muted,.mini,.foot,.empty-note{font-size:14px;color:var(--muted)}.sub{margin:0 0 24px}.admin-nav{display:flex;gap:4px;border-bottom:1px solid var(--line);margin-bottom:24px}.admin-nav button{flex:1;border:0;background:transparent;color:var(--muted);padding:12px 8px;border-bottom:3px solid transparent}.admin-nav button[aria-pressed=true]{border-color:var(--brand);color:var(--brand);font-weight:700}
.stats{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;margin:0 0 20px}.stat{padding:16px 8px;border:1px solid var(--line);border-radius:12px;background:var(--paper);text-align:center}.stat-n{font-size:26px;font-weight:700;color:var(--brand);line-height:1.2}.stat-l{font-size:14px;margin-top:6px}.mini{margin:12px 0 20px}.customer-tools{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:20px 0 12px}.customer-tools label{font-size:14px;font-weight:600;min-width:0}.customer-tools input,.customer-tools select{display:block;width:100%;min-width:0;padding:10px;border:1px solid #bfb5a5;border-radius:8px;background:var(--paper);color:var(--ink);margin-top:6px;min-height:48px}
.customer{background:var(--paper);border:1px solid var(--line);border-radius:12px;margin:12px 0;overflow-wrap:anywhere}.customer>summary{padding:18px;cursor:pointer;list-style:none}.customer>summary::-webkit-details-marker{display:none}.customer-head{display:flex;gap:12px;justify-content:space-between;align-items:start}.customer-head strong{font-size:18px}.access-badge{font-size:13px;color:var(--brand);white-space:nowrap;background:#f0e9dc;padding:2px 8px;border-radius:5px}.customer-meta,.customer-last{display:block;font-size:14px;color:var(--muted);margin-top:5px}.detail-hint{display:block;text-align:right;font-size:14px;color:var(--brand);margin-top:8px}.chevron{display:inline-block;margin-left:6px}.customer[open] .chevron{transform:rotate(180deg)}.customer-body{border-top:1px solid var(--line);padding:0 18px}.customer-body>section{padding:20px 0;border-bottom:1px solid var(--line)}.customer-body>section:last-child{border:0}dl{display:grid;grid-template-columns:96px minmax(0,1fr);gap:8px 12px;margin:8px 0}dt{font-size:14px;color:var(--muted)}dd{margin:0;font-size:14px}.timeline{padding:0;list-style:none;margin:16px 0}.timeline li{display:grid;gap:2px;border-left:2px solid var(--line);padding:0 0 16px 14px}.timeline time{font-size:14px;color:var(--muted)}.timeline span{font-size:16px}.path-list{list-style:none;padding:0}.path-list li{padding:8px 0;border-bottom:1px solid var(--line)}.path-list small{display:block;color:var(--muted)}.export-entry{padding:12px 0;border-bottom:1px solid var(--line)}.export-entry>span{display:block;font-size:14px;color:var(--muted)}.btn{display:inline-block;min-height:44px;padding:8px 16px;border:1px solid var(--line);border-radius:8px;text-decoration:none;font-size:16px}.btn-on{background:var(--brand);color:white}.btn-off{color:#944431;background:transparent}.method-note{margin-top:24px;font-size:14px;color:var(--muted)}.method-note summary{cursor:pointer;padding:12px 0}.foot{margin-top:32px}
.ucard{background:var(--paper);border:1px solid var(--line);border-radius:12px;padding:18px;margin-bottom:24px}.sec-title{margin-top:24px}.ubar{display:grid;grid-template-columns:1fr auto;gap:6px 12px;padding:10px 0;font-size:16px}.ul{grid-column:1;grid-row:1}.uv{grid-column:2;grid-row:1;font-weight:650;color:var(--brand)}.ut{grid-column:1/-1;grid-row:2;height:6px;background:#eee9df;border-radius:4px;overflow:hidden}.uf{display:block;height:100%;background:#9b7547;border-radius:4px}
@media(max-width:480px){.customer-tools{grid-template-columns:1fr}.stats{gap:6px}.stat{padding:12px 4px}.stat-l{font-size:14px}.stat-n{font-size:24px}.customer>summary{padding:16px}.customer-body{padding:0 16px}dl{grid-template-columns:1fr;gap:2px}dd{margin-bottom:8px}}
`;
